# Generated by Django 5.2.4 on 2025-09-14 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_signup_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='membership_level',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
