# Generated by Django 5.2.4 on 2025-09-16 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_remove_profile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('discount_per', models.PositiveIntegerField(help_text='discount %')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
