# Generated by Django 5.2.4 on 2025-09-16 14:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='rental_end_date',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='rental_start_date',
        ),
        migrations.AddField(
            model_name='rental',
            name='dropoff_location',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='rental',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='rental',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='pickup_location',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='rental',
            name='price_per_day',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='rental',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='rental',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='total_price',
            field=models.FloatField(default=0.0),
        ),
    ]
